### ISSUE TITLE
Suggestion for theme changes

### ISSUE THREAD

**Issue by ryuuji89** [gmc-holle/xfdashboard#108]
Was thinking that would be nice to make the xfce panel 1 (usually is the one that serves as taskbar) visible when opening xfdashboard. Also I think would look more tidy if the quicklaunch bar would be in the middle in the left side and extending or regressing its height just to fit the items you have in it (like in gnome 3 shell :P).

**Comment by gmc-holle** [comment]
I don't know what you mean with "[...] to make the xfce panel 1 visible when opening xfdashboard."

But the second suggestion is already possible and depends on the theme. Each theme has at least one layout file defined in line `Layout=` at `xfdashboard.theme`. The layout files define how the primary monitor (and maybe also the secondary monitors) should look like, e.g. where the quicklaunch section is, where the viewpad is etc. 

Suggesting you have already copied the default favourite theme `xfdashboard` to ~/.themes/xfdashboard look at the file `~/.themes/xfdashboard/xfdashboard-1.0/xfdashboard.xml` and search the following lines:

```
<child>
    <object class="XfdashboardQuicklaunch" id="quicklaunch">
        <property name="can-focus">true</property>
        <property name="orientation">vertical</property>
        <property name="y-expand">true</property>
    </object>
</child>
```

There you need to add a new property `y-align` so that the lines will look like:

```
<child>
    <object class="XfdashboardQuicklaunch" id="quicklaunch">
        <property name="can-focus">true</property>
        <property name="orientation">vertical</property>
        <property name="y-expand">true</property>
        <property name="y-align">center</property>
    </object>
</child>
```

This will expand the quicklauch to fetch all available space in vertical axis and to center it vertically with this space.

You can do a lot more things with the layout and you can modify tons of properties. To explain them will go beyond an "issue" here. I can only advice to have a look at the documentation about theming in xfdashboard (http://xfdashboard.froevel.de/theming-unstable.html) and to look at the API documentation of Clutter (https://developer.gnome.org/clutter/1.12) where all properties of all actors are described with their possible values.

**Comment by ryuuji89** [comment]
I was talking about this http://i.imgur.com/JS0qKwm.png to be visible when opening xfdashboard.
Also when using icon view mode in applications the sidebard does not appear.

Thank you for all the info, really helpful.

**Comment by gmc-holle** [comment]
Ok. No that's not possible. The nature of fullscreen windows is to overlap the panel and so does the fullscreen window in xfdashboard. Additionally I think you start xfdashboard because you want to interact with it and not with the panel or you can quit xfdashboard to reach the panel again.

Could you please double-check if your applications does not fit into the view when they are shown in icon mode and you need a scrollbar. If this is the case and the scrollbar is missing then it is a bug :( Could you please file a bug, describe the issue and add a screenshot if this is true?

**Comment by ryuuji89** [comment]
Ok, it was just this idea that xfdashboard can replace fully the whiskers menu plus having it integrated with the whole desktop setup. I m a bit too much into details sometimes, sorry.

I made another issue with screenshot regarding the scrollbar.

**Comment by gmc-holle** [comment]
Thanks, I will have a look at it. Closing this isse.
