### ISSUE TITLE
xfdashboard stretching out to extended monitors

### ISSUE THREAD

**Issue by TyphoidTony** [gmc-holle/xfdashboard#127]
After trying to get this working and looking through the documentation I can't seem to find a way to make xfdashboard only appear on a single monitor. Currently xfdashboard seems to stretch out to all the monitors. Will provide an image link to show what I mean. 

http://i.imgur.com/NXfhYss.png

**Comment by gmc-holle** [comment]
Hi,

yes, that's right. xfdashboard will put its window into fullscreen *and* across a monitors. It will not limit itself to just one monitor, e.g. the primary monitor. That's by design as xfdashboard will keep itself the active window (means steals the focus if the active window is changed, e.g. by ALT+Tab) as long as it is visible so in my opinion it doesn't make sense to limit the window to just one monitor. Even disabling Xinerama on which xfdashboard relies on scretch across all monitor should not help.

So the short answer: Sorry, no, it's not possible.

You can lower the disruption from the elements on the monitor so you can see through it (but dimmed) by creating a new theme and changing the layout for all non-primary monitors and removing all elements - means an empty layout.
