### ISSUE TITLE
TryExec from desktop value not checked

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#151]
Currently the `TryExec` value is ignored - there is no check if the application is runnable. This makes applications visible which should be hidden because the TryExec condition fails.

From [specification](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html):
<table><tr><td>TryExec</td><td>	Path to an executable file on disk used to determine if the program is actually installed. If the path is not an absolute path, the file is looked up in the $PATH environment variable. If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example).</td></tr></table>

This is available in Garcon:
* Function to check wether the desktop file should be visible - checks TryExec also: <https://github.com/xfce-mirror/garcon/blob/master/garcon/garcon-menu-item.c#L573>
* Getter: <https://git.xfce.org/xfce/garcon/tree/garcon/garcon-menu-item.h#n91>
* Enum: <https://github.com/xfce-mirror/garcon/blob/master/garcon/garcon-menu-item.c#L52>

**Comment by gmc-holle** [comment]
Good point. Looks like the virtual function `shoud_show` of class GAppInfo at XfdashboardDesktopAppInfo should be overriden which calls `garcon_menu_element_get_visible` and use this function instead of `xfdashboard_desktop_app_info_get_hidden` and `xfdashboard_desktop_app_info_get_nodisplay`. These both function could be removed instead.

Nothing hard to implement but will take some time.

**Comment by gmc-holle** [comment]
Done. Could you check if it works for you?

**Comment by gsantner** [comment]
Thanks for implementing! :+1:  Tried it with latest HEAD, yes the tested application is now hidden.

BTW: was running sysmonitor at the same time, found xfdashboard (in dashboard view) 40% cpu usage on i5-core. Don't know if it needed it in to 0.7.2 too
