### ISSUE TITLE
Blue theme has no screenshot

### ISSUE THREAD

**Issue by scootergrisen** [gmc-holle/xfdashboard#162]
xfdashboard-blue theme seems to be missing a screenshot.
When you switch between the diffent themes in the list of xfdashboard-settings the text jump for the theme without screenshot.
Perhaps something should be done so that the text will appear the same place even if there is no screenshot for the theme.

**Comment by gmc-holle** [comment]
It would be possible to show an 'missing-image' icon in case no screenshot could be found. But it will not help the texts like name, description etc. from jumping. The texts will also jump if a theme provides a screenshot with a different aspect as other ones, e.g. one has 16:10 but all others 16:9. That's why I mark this issue as `wontfix`.

The only thing we can fix here is to add a screenshot to xfdashboard-blue theme ;)
