### ISSUE TITLE
Movement problems #164

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#167]
#164 Pressing left/right on the most-left/most-right position doesn't move to column0 and next row (or first row if end), instead it just moves to beginning of the current line:

![grafik](https://user-images.githubusercontent.com/6735650/38220753-473c5994-36dc-11e8-92e4-35626ea1b950.png)
pressing right (expected position: pidgin)
![grafik](https://user-images.githubusercontent.com/6735650/38220766-5c4880c4-36dc-11e8-938e-749ba95e1e5c.png)

**Comment by gmc-holle** [comment]
I thought about it and it is not needed to add a new option for this as you can already configure it. Just copy the default key bindings from `/usr/share/xfdashboard/bindings.xml` (or where the default `bindings.xml` is located at your system and change the following lines

```
[...]
        <key code="Left" source="XfdashboardFocusable" when="pressed">selection-move-left</key>
        <key code="Right" source="XfdashboardFocusable" when="pressed">selection-move-right</key>
[...]
```

to

```
[...]
        <key code="Left" source="XfdashboardFocusable" when="pressed">selection-move-previous</key>
        <key code="Right" source="XfdashboardFocusable" when="pressed">selection-move-next</key>
[...]
```

That should get what you want.

The only thing I can do is to simplify overriden the default key binding by allowing just to define the key bindings you want instead of copying the default ones and then to modify them. But that's something different so I mark this one as `wontfix`.

Feel free to re-open this issue if my workaround should not work for you.

**Comment by gsantner** [comment]
yeah, the simplfy solutions sounds not bad!

**Comment by gmc-holle** [comment]
The first enhancement is commited now with 61059defdcd4312232351da266702dab0b37a341

You can now replace the complete content of your user's bindings configuration file at `$HOME/.config/xfdashboard/bindings.xml` with this one:

```
<bindings>
  <key code="Left" source="XfdashboardFocusable" when="pressed">selection-move-previous</key>
  <key code="Right" source="XfdashboardFocusable" when="pressed">selection-move-next</key>
</bindings>
```

**Comment by gsantner** [comment]
thanks! it works correctly in general, only drawbacks are first and last item. e.g. pressing left/prev at application[0] doesnt go to application[length-1]
