### ISSUE TITLE
How to build without live windows?

### ISSUE THREAD

**Issue by SolidHal** [gmc-holle/xfdashboard#174]
I see on the readme it says the live windows are a configurable option. I am interested in disabling this feature to save resources. 
Two main questions, what does xfdashboard look like without live windows?
How do I build xfdashboard without live windows. Theoretically I could choose to not install the packages specified for live windows, but on debian libxfce4ui depends on them.
Thanks!

**Comment by SolidHal** [comment]
After becoming more familiar with auto config and digging through `configure.ac.in` I found the answer to my second question
run:
```
./autogen.sh --disable-xcomposite --disable-xdamage --disable-xinerama
```
to disable live windows and multi monitor support. Testing out now.....

**Comment by gmc-holle** [comment]
Hi SolidHal.

Yes, that's exactly the way I would have told you but you figured it out ;) 

But even it is configurable on xfdashboard side it may still be enabled. It depends on Clutter to show the window content and if Clutter updates the window to perform a live feedback, xfdashboard will show it. That means there can still be live windows even if xfdashboard itself does not support it because XComposite and XDamage are disabled.

Xinerama is for better multi-monitor support.
