### ISSUE TITLE
Grid Icon view

### ISSUE THREAD

**Issue by prp-e** [gmc-holle/xfdashboard#193]
It'd be nice if this amazing piece of software include some grid icon view as well.

**Comment by gmc-holle** [comment]
Hi,

that is already possible and implemented since early versions. But it is the theme's decision if it shows the icons in a list or a grid. The good news is you can override and apply your own CSS styles either globally to all themes or just to a specific theme. It is explained in https://github.com/gmc-holle/xfdashboard/issues/189#issuecomment-621783602 how to do it and the commit message at 7be223df1fc3378691ee851dc7fcc0de3ea312d7 explains where the files must be located and named.

I hope it helps.

Regards,
Stephan
