### ISSUE TITLE
xfdashboard crashes at start-up with GDK backend at Clutter >=1.21

### ISSUE THREAD

**Issue by nonamedotc** [gmc-holle/xfdashboard#73]
I recently upgraded to Fedora 22 and realized xfdashboard does not the nice "overview" anymore. I tried to generate stack traces using GDB, but this is all I got.

```bash
Starting program: /usr/bin/xfdashboard 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

(xfdashboard:6218): GLib-GObject-WARNING **: value "0" of type 'gint' is invalid or out of range for property 'window-scaling-factor' of type 'gint'

(xfdashboard:6218): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'

(xfdashboard:6218): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(xfdashboard:6218): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed

(xfdashboard:6218): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(xfdashboard:6218): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
```

At this point this is all the information I have. If you want to me "troubleshoot" this further, I can post any information I am able to generate.

**Comment by gmc-holle** [comment]
Hi,

first of all, does this happen with xfdashboard 0.3.9 or with the latest git version?

Next question: Do you link against Clutter 1.21 or higher? The message "GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'" indicates that you are using one of these new versions of Clutter which changed the default backend to GDK instead of X11. To check if I'm assume the right source of this problem please try the following command and tell me if xfdashboard is working again:

```
CLUTTER_BACKEND=x11 xfdashboard
```

**Comment by nonamedotc** [comment]
It happens with Xfdashboard 0.3.9.

Absolutely spot on! When I try with CLUTTER_BACKEND=X11, xfdashboard launches without issues. 

# rpm -qa clutter*
clutter-1.21.4-1.fc22.x86_64

Is this already done in the git version or are there plans to incorporate GDK in the future versions?

Thanks for the quick response.

**Comment by gmc-holle** [comment]
Sorry, I haven't done anything against this problem and my system is installing Clutter 1.18. So I have no problem running xfdashboard normally. I can cause the warning when running the command

```
CLUTTER_BACKEND=gdk xfdashboard
```

But I thought it's a Clutter problem because it is experimental at this version (if I remember right).

I'll keep this issue open.

**Comment by gmc-holle** [comment]
A workaround to enforce X11 backend was commited. You might cherry-pick commit 965b6f01210c3c97fe5c02f3e77b7d45e481e75d to package xfdashboard for Fedora 22 successfully.

With this commit this issue is fixed but not the main problem to support Clutter's GDK backend fully.

**Comment by gmc-holle** [comment]
Reopened issue because I need confirmation ;)

Could you please tell me if this fix works for you?

**Comment by nonamedotc** [comment]
Excellent. This commit seems to fix this issue. Thanks! Closing ..
