### ISSUE TITLE
Two UI Issues: Not showing all thumbnails and blinking when switching between workspaces

### ISSUE THREAD

**Issue by Damiox** [gmc-holle/xfdashboard#93]
Hi. 
Before I want to say that this project is just great, and IMHO it needs to be included by default in XFCE.
I see that you are supporting this project actively and that's great.  

I am using xfdashboard daily, building it directly from the git master branch (using currently git version 729bbb9ff2e012ecf995691bb7bd9e510cae0e68), and so far I have found two issues that I will write down below. As my english is rusty, I also recorded a video to make the explanation easy.

Issues:

1. When xfdashboard shows up, it doesn't render the preview windows corresponding to the other applications running in the other workspaces. Thus, if I'm in workspace 4, and I start xfdashboard, it should show all the thumbnails corresponding to all applications in all workspaces. Instead, it shows the thumbnails for the current workspaces and shows icons in workspace 1,2,3. 

2. When xfdashboard switches between two workspaces, it goes off/on like a blink for 0.5-1.5 secs. It would be great if we may remove that blink, so the transition between workspaces is smoother.

Link to my video showing the above issues: https://www.dropbox.com/s/309gwdoufimlgxv/issuevideo1.ogv?dl=0

Thank you,
D

**Comment by gmc-holle** [comment]
Hi Damiox,

thanks for using xfdashboard :) I'm always happy to hear that someone uses it ;)

Don't mind - my english isn't well either. So I hope I can explain the reasons for your issues well enough.  These problems are well known and rely on limitations of the window manager and also on xfdashboard indirectly.

The limitation is that a window which is unmapped (hidden), e.g. it is minimized or placed on an inactive workspace, does not "exist" anymore. Therefore I cannot access it anymore to retrieve its content to display. When xfdashboard starts-up as standalone application (not in daemon mode) it can only access the *visible* windows on the currently active workspace and show their content. All other windows are inaccessible and the fallback, showing their window icon, is used. The only solution would be if I would access the snapshot that newer xfwm4 versions store. But it would be a seperate workaround for each window manager out there.

The blinking when switching workspaces is also known. I believe its cause is that it sometimes takes too long to upload the window contents as textures to the GPU and only if all textures are uploaded xfdashboard's application window is raised and shown again. An idea would be to upload the inital window content asynchronously but as far as I know it is not possible because it has to done in the main thread. I really would like to do this in seperate thread because it also would speed up the start of xfdashboard.

To make a long story short: Your issues are well known but no solution exist. I'm sad to say that :(

Regards,
Stephan
